Update to incluce package-lock

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,6 +13,14 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Verify package-lock.json exists
+        run: |
+          ls -la
+          if [ ! -f package-lock.json ]; then
+            echo "package-lock.json not found!"
+            exit 1
+          fi
+
       - name: Cache Node.js
         id: cache-node
         uses: actions/cache@v3
